version: "3.8"

services:
  foodtasker:
    build: .
    container_name: foodtasker
    ports:
      - "8000:8000"
    volumes:
      - .:/home/python/foodtasker/
      - ~/.aws/:/root/.aws:ro
    command: gunicorn foodtasker.wsgi:application --bind 0.0.0.0:8000
